-- Reference allergies, ingredients, and the 159 Thai recipes are installed by
-- migration 004_import_thai_recipes.sql. User-owned demo records stay local
-- because Supabase auth user IDs are project-specific.
