import { describe,expect,it } from "vitest";
import { normaliseAllergy,validateNewAllergy } from "@/lib/business/allergies";
import { estimateExpiry,getExpiryStatus } from "@/lib/business/expiry";
import { calculateMatch,calculateMissingIngredients } from "@/lib/business/matching";
import { calculateRankScore } from "@/lib/business/ranking";
import { calculateDeduction } from "@/lib/business/deduction";
import { filterRecipes } from "@/lib/business/filtering";
import { demoInventory,recipes } from "@/lib/demo-data";
import type { InventoryItem,Recipe } from "@/lib/types";

const today=new Date("2026-08-05T12:00:00Z");
const baseInventory:InventoryItem[]=[{id:"1",ingredientId:"rice",name:"Rice",category:"Grains",quantity:500,unit:"g",storageLocation:"Pantry",addedDate:"2026-08-01",expiryDate:"2026-09-01",expirySource:"entered"}];
const basic:Recipe={id:"r",name:"Rice meal",description:"",instructions:[],preparationTime:10,difficulty:"Easy",defaultServings:2,dietaryCategory:"Vegan",emoji:"🍚",ingredients:[{ingredientId:"rice",name:"Rice",requiredQuantity:200,unit:"g"},{ingredientId:"carrot",name:"Carrot",requiredQuantity:100,unit:"g"}]};

describe("allergy management",()=>{it("normalises case and whitespace",()=>expect(normaliseAllergy("  Tree   NUTS ")).toBe("tree nuts"));it("rejects blank values",()=>expect(validateNewAllergy("  ",[]).ok).toBe(false));it("rejects normalised duplicates",()=>expect(validateNewAllergy(" peanuts ",["Peanuts"]).ok).toBe(false))});
describe("expiry",()=>{it("classifies expired, today, soon and fresh",()=>{expect(getExpiryStatus("2026-08-04",today).status).toBe("expired");expect(getExpiryStatus("2026-08-05",today).status).toBe("today");expect(getExpiryStatus("2026-08-08",today).status).toBe("soon");expect(getExpiryStatus("2026-08-09",today).status).toBe("fresh")});it("estimates using category and location",()=>expect(estimateExpiry("2026-08-01","Meat","Refrigerator")).toBe("2026-08-03"))});
describe("recipe matching",()=>{it("returns a partial match",()=>expect(calculateMatch(basic,baseInventory,today)).toMatchObject({percentage:50,availableCount:1,totalRequired:2}));it("returns 100% match",()=>expect(calculateMatch({...basic,ingredients:[basic.ingredients[0]]},baseInventory,today).percentage).toBe(100));it("returns 0% match",()=>expect(calculateMatch(basic,[],today).percentage).toBe(0));it("ignores optional ingredients in denominator",()=>expect(calculateMatch({...basic,ingredients:[basic.ingredients[0],{...basic.ingredients[1],isOptional:true}]},baseInventory,today)).toMatchObject({percentage:100,totalRequired:1}));it("does not count expired inventory",()=>expect(calculateMatch({...basic,ingredients:[basic.ingredients[0]]},[{...baseInventory[0],expiryDate:"2026-08-04"}],today).percentage).toBe(0));it("defines recipes with no required ingredients as 100%",()=>expect(calculateMatch({...basic,ingredients:[]},[],today)).toMatchObject({percentage:100,totalRequired:0}));it("returns missing ingredient details",()=>expect(calculateMissingIngredients(basic,baseInventory,today).map(x=>x.name)).toEqual(["Carrot"]))});
describe("filtering",()=>{it("excludes the peanut recipe for Alex",()=>expect(filterRecipes(recipes,["Peanuts"],"No restriction").some(r=>r.id==="peanut-noodle")).toBe(false));it("applies vegetarian filtering",()=>expect(filterRecipes(recipes,[],"Vegetarian").every(r=>["Vegetarian","Vegan"].includes(r.dietaryCategory))).toBe(true))});
describe("ranking",()=>{it("favours a high match over a low match with expiry bonus",()=>expect(calculateRankScore(90,0,1,30)).toBeGreaterThan(calculateRankScore(35,3,4,10)));it("adds a near-expiry bonus",()=>expect(calculateRankScore(80,1,1,20)).toBeGreaterThan(calculateRankScore(80,0,1,20)));it("penalises excessive missing ingredients",()=>expect(calculateRankScore(60,1,4,20)).toBeLessThan(calculateRankScore(60,0,1,20)));it("uses prep time as a small tie-breaker",()=>expect(calculateRankScore(80,0,1,10)).toBeGreaterThan(calculateRankScore(80,0,1,30)))});
describe("inventory deduction",()=>{it("deducts sufficient inventory",()=>expect(calculateDeduction({...basic,ingredients:[basic.ingredients[0]]},baseInventory,2)).toMatchObject({ok:true,inventory:[{quantity:300}]}));it("rejects insufficient inventory without mutation",()=>{const result=calculateDeduction({...basic,ingredients:[{...basic.ingredients[0],requiredQuantity:600}]},baseInventory,2);expect(result.ok).toBe(false);expect(result.inventory[0].quantity).toBe(500)});it("removes a zero-balance record",()=>expect(calculateDeduction({...basic,ingredients:[{...basic.ingredients[0],requiredQuantity:500}]},baseInventory,2).inventory).toHaveLength(0));it("deducts multiple ingredients",()=>{const inv=[...baseInventory,{...baseInventory[0],id:"2",ingredientId:"carrot",name:"Carrot",quantity:100}];expect(calculateDeduction(basic,inv,2).inventory).toMatchObject([{quantity:300}])});it("scales servings",()=>expect(calculateDeduction({...basic,ingredients:[basic.ingredients[0]]},baseInventory,4).inventory[0].quantity).toBe(100));it("prevents partial updates when one item is short",()=>{const inv=[...baseInventory,{...baseInventory[0],id:"2",ingredientId:"carrot",name:"Carrot",quantity:50}];const result=calculateDeduction(basic,inv,2);expect(result.ok).toBe(false);expect(result.inventory).toEqual(inv)})});

describe("realistic demo fixture",()=>{it("produces recommendations from seeded inventory",()=>expect(filterRecipes(recipes,["Peanuts"],"No restriction").length).toBe(8));it("has at least one full match",()=>expect(recipes.some(r=>calculateMatch(r,demoInventory).percentage===100)).toBe(true))});
