import { addDays, formatISO } from "date-fns";
import type {
  HistoryItem,
  Ingredient,
  InventoryItem,
  Profile,
  Recipe,
  ShoppingItem,
  Unit,
} from "./types";

const day = (offset: number) =>
  formatISO(addDays(new Date(), offset), { representation: "date" });

export const ingredients: Ingredient[] = [
  ["chicken", "Chicken breast", "Meat"],
  ["broccoli", "Broccoli", "Vegetables"],
  ["carrot", "Carrot", "Vegetables"],
  ["mushroom", "Mushroom", "Vegetables"],
  ["egg", "Eggs", "Dairy", ["Eggs"]],
  ["tomato", "Tomato", "Vegetables"],
  ["pasta", "Pasta", "Grains", ["Wheat"]],
  ["rice", "Rice", "Grains"],
  ["spinach", "Spinach", "Vegetables"],
  ["cheese", "Cheese", "Dairy", ["Milk"]],
  ["bread", "Bread", "Grains", ["Wheat"]],
  ["onion", "Onion", "Vegetables"],
  ["milk", "Milk", "Dairy", ["Milk"]],
  ["peanut", "Peanut butter", "Condiments", ["Peanuts"]],
  ["noodle", "Noodles", "Grains", ["Wheat"]],
  ["soy", "Soy sauce", "Condiments", ["Soy"]],
  ["oil", "Cooking oil", "Condiments"],
  ["garlic", "Garlic", "Vegetables"],
].map(([id, name, category, allergens]) => ({
  id: id as string,
  name: name as string,
  category: category as string,
  allergens: allergens as string[] | undefined,
}));

const ri = (
  ingredientId: string,
  requiredQuantity: number,
  unit: Unit,
  isOptional = false,
) => {
  const ingredient = ingredients.find((item) => item.id === ingredientId)!;
  return {
    ingredientId,
    name: ingredient.name,
    requiredQuantity,
    unit,
    isOptional,
    allergens: ingredient.allergens,
  };
};

export const recipes: Recipe[] = [
  {
    id: "stir-fry",
    name: "Chicken & vegetable stir-fry",
    description:
      "A quick, colourful weeknight stir-fry that makes the most of crisp vegetables.",
    instructions: [
      "Slice the chicken and vegetables.",
      "Sear chicken in oil until cooked through.",
      "Add vegetables and soy sauce; toss for 4 minutes.",
      "Serve immediately.",
    ],
    preparationTime: 25,
    difficulty: "Easy",
    defaultServings: 2,
    dietaryCategory: "No restriction",
    emoji: "🥦",
    ingredients: [
      ri("chicken", 300, "g"),
      ri("broccoli", 200, "g"),
      ri("carrot", 120, "g"),
      ri("soy", 30, "ml"),
      ri("oil", 15, "ml", true),
    ],
  },
  {
    id: "omelette",
    name: "Mushroom omelette",
    description: "Fluffy eggs folded around savoury mushrooms and greens.",
    instructions: [
      "Slice and sauté mushrooms.",
      "Whisk eggs and pour into the pan.",
      "Add spinach, fold, and cook until just set.",
    ],
    preparationTime: 15,
    difficulty: "Easy",
    defaultServings: 2,
    dietaryCategory: "Vegetarian",
    emoji: "🍳",
    ingredients: [
      ri("egg", 4, "pieces"),
      ri("mushroom", 150, "g"),
      ri("spinach", 60, "g"),
    ],
  },
  {
    id: "tomato-pasta",
    name: "Tomato pasta",
    description: "Comforting pasta in a bright, garlicky tomato sauce.",
    instructions: [
      "Boil pasta until al dente.",
      "Cook garlic and tomato into a sauce.",
      "Toss together and season.",
    ],
    preparationTime: 20,
    difficulty: "Easy",
    defaultServings: 2,
    dietaryCategory: "Vegan",
    emoji: "🍝",
    ingredients: [
      ri("pasta", 200, "g"),
      ri("tomato", 300, "g"),
      ri("garlic", 10, "g"),
    ],
  },
  {
    id: "veg-rice",
    name: "Vegetable fried rice",
    description: "A fast pantry-friendly bowl loaded with vegetables.",
    instructions: [
      "Sauté vegetables.",
      "Add cooked rice and soy sauce.",
      "Stir-fry on high heat for 3 minutes.",
    ],
    preparationTime: 18,
    difficulty: "Easy",
    defaultServings: 2,
    dietaryCategory: "Vegan",
    emoji: "🍚",
    ingredients: [
      ri("rice", 250, "g"),
      ri("carrot", 100, "g"),
      ri("broccoli", 120, "g"),
      ri("soy", 20, "ml"),
    ],
  },
  {
    id: "spinach-sandwich",
    name: "Spinach & cheese sandwich",
    description: "A golden toasted sandwich with a fresh spinach centre.",
    instructions: [
      "Layer bread with spinach and cheese.",
      "Toast until crisp and melted.",
    ],
    preparationTime: 10,
    difficulty: "Easy",
    defaultServings: 1,
    dietaryCategory: "Vegetarian",
    emoji: "🥪",
    ingredients: [
      ri("bread", 2, "pieces"),
      ri("spinach", 50, "g"),
      ri("cheese", 40, "g"),
    ],
  },
  {
    id: "chicken-bowl",
    name: "Chicken rice bowl",
    description: "A balanced bowl with tender chicken and fresh vegetables.",
    instructions: [
      "Cook chicken until golden.",
      "Warm rice and steam broccoli.",
      "Assemble and drizzle with soy sauce.",
    ],
    preparationTime: 30,
    difficulty: "Medium",
    defaultServings: 2,
    dietaryCategory: "No restriction",
    emoji: "🥗",
    ingredients: [
      ri("chicken", 300, "g"),
      ri("rice", 250, "g"),
      ri("broccoli", 150, "g"),
      ri("soy", 20, "ml"),
    ],
  },
  {
    id: "carrot-soup",
    name: "Silky carrot soup",
    description: "A warming, naturally sweet soup with a smooth finish.",
    instructions: [
      "Chop carrot and onion.",
      "Simmer in water until tender.",
      "Blend until smooth and season.",
    ],
    preparationTime: 35,
    difficulty: "Easy",
    defaultServings: 4,
    dietaryCategory: "Vegan",
    emoji: "🥕",
    ingredients: [
      ri("carrot", 500, "g"),
      ri("onion", 150, "g"),
      ri("garlic", 10, "g", true),
    ],
  },
  {
    id: "egg-rice",
    name: "Egg fried rice",
    description: "A satisfying classic ready in under twenty minutes.",
    instructions: [
      "Scramble eggs and set aside.",
      "Stir-fry rice with vegetables.",
      "Return eggs, season, and toss.",
    ],
    preparationTime: 18,
    difficulty: "Easy",
    defaultServings: 2,
    dietaryCategory: "Vegetarian",
    emoji: "🍚",
    ingredients: [
      ri("rice", 250, "g"),
      ri("egg", 3, "pieces"),
      ri("carrot", 80, "g"),
      ri("soy", 20, "ml"),
    ],
  },
  {
    id: "peanut-noodle",
    name: "Peanut noodle bowl",
    description: "Creamy, savoury noodles with crunchy vegetables.",
    instructions: [
      "Boil noodles.",
      "Whisk peanut butter with soy sauce.",
      "Toss noodles in sauce and add vegetables.",
    ],
    preparationTime: 20,
    difficulty: "Easy",
    defaultServings: 2,
    dietaryCategory: "Vegan",
    emoji: "🥜",
    ingredients: [
      ri("noodle", 200, "g"),
      ri("peanut", 60, "g"),
      ri("soy", 20, "ml"),
      ri("carrot", 80, "g"),
    ],
  },
];

export const demoProfile: Profile = {
  displayName: "Alex",
  dietaryPreference: "No restriction",
  healthGoal: "Balanced diet",
  setupCompleted: true,
  allergies: ["Peanuts"],
};
export const demoInventory: InventoryItem[] = [
  {
    id: "inv-chicken",
    ingredientId: "chicken",
    name: "Chicken breast",
    category: "Meat",
    quantity: 450,
    unit: "g",
    storageLocation: "Refrigerator",
    addedDate: day(-1),
    expiryDate: day(1),
    expirySource: "entered",
  },
  {
    id: "inv-broccoli",
    ingredientId: "broccoli",
    name: "Broccoli",
    category: "Vegetables",
    quantity: 300,
    unit: "g",
    storageLocation: "Refrigerator",
    addedDate: day(-4),
    expiryDate: day(2),
    expirySource: "estimated",
  },
  {
    id: "inv-carrot",
    ingredientId: "carrot",
    name: "Carrot",
    category: "Vegetables",
    quantity: 600,
    unit: "g",
    storageLocation: "Refrigerator",
    addedDate: day(-2),
    expiryDate: day(5),
    expirySource: "entered",
  },
  {
    id: "inv-rice",
    ingredientId: "rice",
    name: "Rice",
    category: "Grains",
    quantity: 900,
    unit: "g",
    storageLocation: "Pantry",
    addedDate: day(-20),
    expiryDate: day(160),
    expirySource: "estimated",
  },
  {
    id: "inv-egg",
    ingredientId: "egg",
    name: "Eggs",
    category: "Dairy",
    quantity: 8,
    unit: "pieces",
    storageLocation: "Refrigerator",
    addedDate: day(-4),
    expiryDate: day(3),
    expirySource: "entered",
  },
  {
    id: "inv-spinach",
    ingredientId: "spinach",
    name: "Spinach",
    category: "Vegetables",
    quantity: 120,
    unit: "g",
    storageLocation: "Refrigerator",
    addedDate: day(-5),
    expiryDate: day(-1),
    expirySource: "entered",
  },
  {
    id: "inv-soy",
    ingredientId: "soy",
    name: "Soy sauce",
    category: "Condiments",
    quantity: 250,
    unit: "ml",
    storageLocation: "Pantry",
    addedDate: day(-30),
    expiryDate: day(80),
    expirySource: "entered",
  },
  {
    id: "inv-mushroom",
    ingredientId: "mushroom",
    name: "Mushroom",
    category: "Vegetables",
    quantity: 180,
    unit: "g",
    storageLocation: "Refrigerator",
    addedDate: day(-2),
    expiryDate: day(2),
    expirySource: "estimated",
  },
];
export const demoShopping: ShoppingItem[] = [
  {
    id: "shop-1",
    name: "Wholegrain bread",
    quantity: 1,
    unit: "packs",
    isPurchased: false,
  },
];
export const demoHistory: HistoryItem[] = [
  {
    id: "hist-1",
    recipeId: "tomato-pasta",
    recipeName: "Tomato pasta",
    cookedAt: day(-2) + "T19:30:00Z",
    servings: 2,
    summary: { Pasta: 200, Tomato: 300 },
  },
];
