import { addDays, formatISO } from "date-fns";
import type {
  HistoryItem,
  Ingredient,
  InventoryItem,
  Profile,
  Recipe,
  ShoppingItem,
} from "./types";
import { thaiRecipes } from "./thai-recipes";

const day = (offset: number) =>
  formatISO(addDays(new Date(), offset), { representation: "date" });

export const ingredients: Ingredient[] = [
  ["chicken", "อกไก่", "Meat"],
  ["halal-chicken", "อกไก่ฮาลาล", "Meat"],
  ["broccoli", "บรอกโคลี", "Vegetables"],
  ["carrot", "แครอท", "Vegetables"],
  ["mushroom", "เห็ด", "Vegetables"],
  ["egg", "ไข่", "Dairy", ["Eggs"]],
  ["tomato", "มะเขือเทศ", "Vegetables"],
  ["pasta", "พาสต้า", "Grains", ["Wheat"]],
  ["rice", "ข้าว", "Grains"],
  ["spinach", "ผักโขม", "Vegetables"],
  ["cheese", "ชีส", "Dairy", ["Milk"]],
  ["bread", "ขนมปัง", "Grains", ["Wheat"]],
  ["onion", "หอมหัวใหญ่", "Vegetables"],
  ["milk", "นม", "Dairy", ["Milk"]],
  ["peanut", "เนยถั่วลิสง", "Condiments", ["Peanuts"]],
  ["noodle", "เส้นก๋วยเตี๋ยว", "Grains", ["Wheat"]],
  ["soy", "ซีอิ๊ว", "Condiments", ["Soy"]],
  ["oil", "น้ำมันปรุงอาหาร", "Condiments"],
  ["garlic", "กระเทียม", "Vegetables"],
].map(([id, name, category, allergens]) => ({
  id: id as string,
  name: name as string,
  category: category as string,
  allergens: allergens as string[] | undefined,
}));

export const recipes: Recipe[] = thaiRecipes;

export const demoProfile: Profile = {
  displayName: "Alex",
  dietaryPreference: "No restriction",
  healthGoal: "Balanced diet",
  setupCompleted: true,
  allergies: ["Peanuts"],
};
export const demoInventory: InventoryItem[] = [
  {
    id: "inv-halal-chicken",
    ingredientId: "halal-chicken",
    name: "อกไก่ฮาลาล",
    category: "Meat",
    quantity: 500,
    unit: "g",
    storageLocation: "Refrigerator",
    addedDate: day(-1),
    expiryDate: day(2),
    expirySource: "entered",
    notes: "ผลิตภัณฑ์ได้รับการรับรองฮาลาล",
  },
  {
    id: "inv-chicken",
    ingredientId: "chicken",
    name: "อกไก่",
    category: "Meat",
    quantity: 450,
    unit: "g",
    storageLocation: "Refrigerator",
    addedDate: day(-1),
    expiryDate: day(1),
    expirySource: "entered",
  },
  {
    id: "inv-broccoli",
    ingredientId: "broccoli",
    name: "บรอกโคลี",
    category: "Vegetables",
    quantity: 300,
    unit: "g",
    storageLocation: "Refrigerator",
    addedDate: day(-4),
    expiryDate: day(2),
    expirySource: "estimated",
  },
  {
    id: "inv-carrot",
    ingredientId: "carrot",
    name: "แครอท",
    category: "Vegetables",
    quantity: 600,
    unit: "g",
    storageLocation: "Refrigerator",
    addedDate: day(-2),
    expiryDate: day(5),
    expirySource: "entered",
  },
  {
    id: "inv-rice",
    ingredientId: "rice",
    name: "ข้าว",
    category: "Grains",
    quantity: 900,
    unit: "g",
    storageLocation: "Pantry",
    addedDate: day(-20),
    expiryDate: day(160),
    expirySource: "estimated",
  },
  {
    id: "inv-egg",
    ingredientId: "egg",
    name: "ไข่",
    category: "Dairy",
    quantity: 8,
    unit: "pieces",
    storageLocation: "Refrigerator",
    addedDate: day(-4),
    expiryDate: day(3),
    expirySource: "entered",
  },
  {
    id: "inv-spinach",
    ingredientId: "spinach",
    name: "ผักโขม",
    category: "Vegetables",
    quantity: 120,
    unit: "g",
    storageLocation: "Refrigerator",
    addedDate: day(-5),
    expiryDate: day(-1),
    expirySource: "entered",
  },
  {
    id: "inv-soy",
    ingredientId: "soy",
    name: "ซีอิ๊ว",
    category: "Condiments",
    quantity: 250,
    unit: "ml",
    storageLocation: "Pantry",
    addedDate: day(-30),
    expiryDate: day(80),
    expirySource: "entered",
  },
  {
    id: "inv-mushroom",
    ingredientId: "mushroom",
    name: "เห็ด",
    category: "Vegetables",
    quantity: 180,
    unit: "g",
    storageLocation: "Refrigerator",
    addedDate: day(-2),
    expiryDate: day(2),
    expirySource: "estimated",
  },
];
export const demoShopping: ShoppingItem[] = [
  {
    id: "shop-1",
    name: "ขนมปังโฮลเกรน",
    quantity: 1,
    unit: "packs",
    isPurchased: false,
  },
];
export const demoHistory: HistoryItem[] = [
  {
    id: "hist-1",
    recipeId: "tomato-pasta",
    recipeName: "มะเขือเทศ pasta",
    cookedAt: day(-2) + "T19:30:00Z",
    servings: 2,
    summary: { พาสต้า: 200, มะเขือเทศ: 300 },
  },
];
